name: Test Core Functionality
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run tests
        run: pytest tests/test_core_functionality.py